### ISSUE TITLE
A weird crash bug involving deletion

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/realm-book-example#12]
![screenshot from 2017-12-14 17-23-28](https://user-images.githubusercontent.com/11718392/34058008-cbd360ec-e1d9-11e7-92fe-bb6a77d4c1f0.png)

Theoretically this should never happen, but apparently it does.

Investigate.

**Comment by Zhuinden** [comment]
```
12-15 21:00:35.497 2524-2524/com.zhuinden.realmbookexample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.zhuinden.realmbookexample, PID: 2524
                                                                             java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
                                                                                 at io.realm.internal.UncheckedRow.nativeGetString(Native Method)
                                                                                 at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:157)
                                                                                 at io.realm.BookRealmProxy.realmGet$title(BookRealmProxy.java:131)
                                                                                 at com.zhuinden.realmbookexample.data.entity.Book.getTitle(Book.java:33)
                                                                                 at com.zhuinden.realmbookexample.paths.books.BooksAddBookView.bind(BooksAddBookView.java:86)
                                                                                 at com.zhuinden.realmbookexample.paths.books.BooksActivity.showEditBookDialog(BooksActivity.java:134)
                                                                                 at com.zhuinden.realmbookexample.paths.books.BooksPresenter.showEditDialog(BooksPresenter.java:71)
                                                                                 at com.zhuinden.realmbookexample.paths.books.BooksAdapter$BookViewHolder$2.onClick(BooksAdapter.java:105)
```

Amazingly, it seems to happen if I... uh... delete from the Realm then click quickly.

**Comment by Zhuinden** [comment]
...I'll just add a validity check before the bind...

**Comment by Zhuinden** [comment]
Worked around in https://github.com/Zhuinden/realm-book-example/commit/8bb7e578951f482097cd29e8015aa4839ed74296
